version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ten meki
           cd meki
           bash lol.sh  
  
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
